[build]
  base = "client"
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/api/paste"
  to = "/.netlify/functions/paste"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_BASE = "https://your-deployment.netlify.app"