[build]
  base = "."
  publish = "client/build"
  command = "cd client && npm install && npm run build && cd ../netlify/functions && npm install"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/paste"
  to = "/.netlify/functions/paste"
  status = 200

[[redirects]]
  from = "/api/user/pastes"
  to = "/.netlify/functions/user-pastes"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200